BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB
    BBBB BBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

  XXXXXXX
    XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX XXXXX
      XXXXXXXXXXXXXXXXX XXXXXXXX
    X
  XXXXXXXX
  XXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
         #

        BB BBBBBBBBBBBBB
          XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX
            XXXXXXXXXXXXXXXX
            XXXXXXXX XX XXXXXX XXXXXX XXX XXXXX XX XXX XXXXXXXXX
            XX XXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXX
        BBBB
          XXXX XXXXXXXXXXXXXXXXXXXXXX

            XXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            BBB BBBB BB BBBBBBBBBBBBBBBBBBBBB
              XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXXXXXX
                BBBBBBBBBB
                XXXX XXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXX

                    XXXX XXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXFFFFFFFFFFFFFFFFXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXX
                    XXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                    XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBB BBBBBBBX  XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX
                    XXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXXX
            BBBBBB


            XXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXX XXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            
            XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

          XXXXXX
        BBBBB
      XXXXXX
    XXXXXXXXXX
  XXXXXXX
BBBBBBBB