BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB
  BBBB BBBBBB
  XXXXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX

  XXXXXX
   XXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
              XXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXX
            XXXXXX XXXXXXXXXXXXX XXXXXXX XXXXXXBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX X XXXXXXXXX
            XXXFFFFFFFFFFFFFFFFXXXX
            XXXXXXXXX XX X XXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
              XXXX
              XXXXXXXXXXX XXXXXX X XXXXXXFFFFFXXXXXXXXXXXXXXXX
              XXXXXXXXXXX XXX X XXXXXXXXXXXXXXXXXXXXXX
            BBBBB


          XXXXXX
          XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBB
              XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
            BBBB
              XXXXXXXXX XXXXXX XX XXXXXXXXXXXXXXFFFFFFF FF FFFFFFFXXXXXXXXXXXXXXXX XXXXX
            BBBBB
            XXXX
              XXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXXXXXXXXFFFFFFF FF FFFFFFFXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXX XXXXXXXXXXXXXXXXXXXFFFFFFF FF FFFFFFFXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBB XXXXXXXXX BBBBBXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXX XX XXX XXXXXXXXXXXXXXXXXFFFFFFF FF FFFFFFFXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBB XXXXXXXXX BBBBBXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXFFFFFFF FF FFFFFFFXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
      
    XXXXXX
  XXXXXX
XXXXXXXXXX
XXXXXXX
BBBBBBBB
