# Generated by Django 3.2.13 on 2022-09-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_auto_20220924_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
