# Generated by Django 3.2.13 on 2022-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_job_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
