# Generated by Django 3.2.13 on 2022-09-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_alter_company_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applications',
            name='resume',
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='type',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='applications',
            name='apply_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ApplicantsResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('pdf', 'pdf'), ('docx', 'docx')], default='pdf', max_length=200)),
                ('file', models.FileField(null=True, upload_to='careers_jobs_resume/%Y/%m/%d/')),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='careers.applications')),
            ],
        ),
    ]
