# Generated by Django 3.2.13 on 2022-09-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_auto_20220925_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.applicant')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='careers.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.job')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantsResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('pdf', 'pdf'), ('docx', 'docx')], default='pdf', max_length=200)),
                ('file', models.FileField(null=True, upload_to='careers_jobs_resume/%Y/%m/%d/')),
                ('application', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='careers.applications')),
            ],
        ),
    ]
