# Generated by Django 3.2.13 on 2022-10-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0011_applicantsresume_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='role',
            field=models.CharField(default='', max_length=250),
        ),
    ]
