BBBB BBBBBBBBBBBBB

BBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
        BBB BBBBBBBBBBBB BB BBBBBBBBBBBBB
          BB BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB
            XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXX
          BBBB
            XXXXXXX XXXXXXXXXXXXXXXXXX
          BBBBB
        BBBBBB
      XXXXXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFF
    XXXXXX

    XXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFF
    XXXXXX
  XXXXXX
XXXXXX

XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XX
XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XX

XXXX XXXXX X XXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXX XXXXX X XXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXX XX
XXXXXX