BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXX X XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                    XXXXXXX
                      XXXX
                        XXXXXXXXXX
                        XXXXXXXXX

                        XXXXXXXXXXXXXX
                        XXXXXXXXXXXXXX

                        XXXXXXXXXXXXXXXX
                      XXXXX
                    XXXXXXXX
                    XXXXXXX
                      BBB BBBBBBB BB BBBBBBBB
                      XXXX
                        XXXXXXXXX
                        XXXXXXXXX

                        XXXXXXXXX
                        XXXXX XXXXX

                        XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBB BBBBBBBBBBXXXXXXXXXXXXXXX
                      XXXXX
                      BBBBBB
                    XXXXXXXX
                  XXXXXXXX

                  XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                XXXXXX
              XXXXXX

            XXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBB
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
