# Generated by Django 3.2.13 on 2022-09-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_created_at', models.CharField(default='', max_length=250)),
                ('processed_at', models.CharField(default='', max_length=250)),
                ('dispatched_at', models.CharField(default='', max_length=250)),
                ('shipped_at', models.CharField(default='', max_length=250)),
                ('delivered_at', models.CharField(default='', max_length=250)),
                ('created_at', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
