# Generated by Django 3.2.13 on 2022-09-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='tracking_number',
            field=models.CharField(default='', max_length=250),
        ),
    ]
