# Generated by Django 3.2.13 on 2022-09-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0002_ordertracking_tracking_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertracking',
            old_name='created_at',
            new_name='active_status',
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='delivery_comment',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='dispatched_comment',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='processing_comment',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='shipping_comment',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='tracking_number',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
