# Generated by Django 3.2.13 on 2022-09-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0004_remove_ordertracking_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='active_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Dispatched', 'Dispatched'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=100),
        ),
    ]
