# Generated by Django 3.2.13 on 2022-09-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_tracking', '0005_ordertracking_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='active_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Dispatched', 'Dispatched'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=500),
        ),
    ]
