# Generated by Django 3.0.6 on 2020-06-08 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', models.TextField(default='N/A')),
                ('image', models.ImageField(null=True, upload_to='category_image')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], default='Image', max_length=200)),
                ('file', models.FileField(null=True, upload_to='product_attachments')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='delivery_available',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pickup_available',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_option',
            field=models.CharField(choices=[('Pickup Available', 'Pickup Available'), ('Delivery Available', 'Delivery Available'), ('Both', 'Both')], default='Both', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_option',
            field=models.CharField(choices=[('Fixed Price', 'Fixed Price'), ('Sliding Scale Depending On Volume', 'Sliding Scale Depending On Volume'), ('Contact Us', 'Contact Us')], default='Fixed Price', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='ProductAttachments',
        ),
        migrations.AddField(
            model_name='productattachment',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
    ]
