# Generated by Django 3.0.6 on 2020-06-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200608_2148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductAttachment',
            new_name='Attachment',
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
