# Generated by Django 3.0.6 on 2020-06-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200619_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(error_messages={'required': 'Name can not be blank'}, max_length=50, unique=True),
        ),
    ]
