# Generated by Django 3.0.6 on 2020-11-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_variant_option_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optionvalue',
            unique_together={('value', 'option_type')},
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'option_value')},
        ),
        migrations.RemoveField(
            model_name='variant',
            name='color',
        ),
    ]
