# Generated by Django 3.0.6 on 2020-11-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20201125_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='quantity',
            new_name='stock',
        ),
    ]
