# Generated by Django 3.0.6 on 2020-11-25 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20201125_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=9, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
