# Generated by Django 3.2.13 on 2022-07-21 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='N/A', max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('sold_id', models.CharField(default='N/A', max_length=100)),
                ('ad_fees', models.CharField(default='N/A', max_length=100)),
                ('sales', models.CharField(blank=True, default='N/A', max_length=32, null=True)),
                ('price_range', models.CharField(blank=True, default='N/A', max_length=32, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=32, null=True)),
                ('paid', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_schedule', models.BooleanField(default=False)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listings', models.ManyToManyField(to='products.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variants', models.ManyToManyField(to='products.Variant')),
            ],
        ),
    ]
