# Generated by Django 3.2.13 on 2022-09-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
