# Generated by Django 3.2.13 on 2022-10-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_campaign_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='tz',
            field=models.CharField(blank=True, default='America/New_York', max_length=150, null=True),
        ),
    ]
