# Generated by Django 3.2.13 on 2022-10-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_campaign_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='active_cmd',
            field=models.CharField(blank=True, default='user', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='schedule_cmd',
            field=models.CharField(blank=True, default='user', max_length=150, null=True),
        ),
    ]
