# Generated by Django 3.2.13 on 2022-07-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchatattachment',
            name='file',
            field=models.FileField(null=True, upload_to='chat_attachments/documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='imagechatattachment',
            name='file',
            field=models.FileField(null=True, upload_to='chat_attachments/images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='videochatattachment',
            name='file',
            field=models.FileField(null=True, upload_to='chat_attachments/videos/%Y/%m/%d/'),
        ),
    ]
