# Generated by Django 3.2.13 on 2022-07-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20220722_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchatattachment',
            name='message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.message'),
        ),
        migrations.AlterField(
            model_name='imagechatattachment',
            name='message',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.message'),
        ),
    ]
