# Generated by Django 3.2.13 on 2022-07-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_videochatattachment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_uid',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
