# Generated by Django 3.2.13 on 2022-07-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_chat_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attached_media_type',
            field=models.CharField(default='video', max_length=200),
        ),
    ]
