# Generated by Django 3.2.13 on 2022-09-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_message_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attached_media_type',
            field=models.CharField(default='Image', max_length=200),
        ),
    ]
