# Generated by Django 3.2.13 on 2022-09-09 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='occupants',
        ),
    ]
