# Generated by Django 3.2.13 on 2022-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20220920_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.CharField(default='', editable=False, max_length=250, primary_key=True, serialize=False),
        ),
    ]
