# Generated by Django 3.2.13 on 2022-09-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='event',
            field=models.CharField(default='text', max_length=512),
        ),
    ]
