# Generated by Django 3.2.13 on 2022-09-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_message_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchatattachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('document', 'document')], default='Document', max_length=200),
        ),
        migrations.AlterField(
            model_name='imagechatattachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('document', 'document')], default='Image', max_length=200),
        ),
        migrations.AlterField(
            model_name='videochatattachment',
            name='attachment_type',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video'), ('document', 'document')], default='Video', max_length=200),
        ),
    ]
