BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB

  XXXX XXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXX X XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXX XXXXX

            XXXXXX
            XXXX XXXXXXXXXXXXXXX
              XXXXX XXXXXX X XBBB BBBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXX
                    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
                  XXXXXX
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBB
                XXXXXX
              XXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
BBBBBBBB
