BBBB BBBBBBBBBBBBB

BBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFF
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFF
XXXXXX


BB BBBBBBBBBBBBBBBB BB BBBB
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX
      XXXX XXXXXXXXXXXBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFF FFFFF
      XXXXXX
      BB BBBBBBBBBBBBBBBBBBBBB
        XXXX XXXXXXXXXXXXXX
          XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
          XXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
            BBB BBBB BB BBBBB
              XXXXXXX XXXXXXXXX XXXXXXXXXXX
            BBBBBB
          XXXXXXXXX
        XXXXXX
      BBBB
        XXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX XX
      BBBBB
    XXXXXX
  XXXXXX
BBBB
  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX
BBBBB

XXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFF FFFFFFF
    XXXXXX

    XXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFF FFFFF FFFFFFFFF
    XXXXXX

    XXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFF FFFFF FFFFFFFFF
    XXXXXX

    XXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFF
    XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
  FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFF
XXXXXX

XXXX XXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
  
XXXXXX

BB BBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    
  XXXXXX

  XXXX XXXXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
    
  XXXXXX
BBBBB
XXXX XXXXX X XXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXX XXXXX X XXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXX XX
XXXXXX