# Generated by Django 3.2.13 on 2022-07-26 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refunds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(editable=False, max_length=250)),
                ('refund_id', models.CharField(editable=False, max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('related_charge', models.CharField(max_length=250)),
                ('refund_reason', models.TextField(blank=True, editable=False, max_length=1000, null=True)),
                ('status', models.CharField(editable=False, max_length=32)),
            ],
        ),
    ]
