# Generated by Django 3.2.13 on 2022-07-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunds',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='refunds',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
