# Generated by Django 3.2.13 on 2022-07-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220726_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunds',
            name='currency',
            field=models.CharField(blank=True, default='usd', max_length=250, null=True),
        ),
    ]
