# Generated by Django 3.2.13 on 2022-07-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_proof_of_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proof_of_business',
            field=models.FileField(null=True, upload_to='business_ownership_attachments'),
        ),
    ]
