# Generated by Django 3.2.13 on 2022-07-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220721_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biz_info_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
