# Generated by Django 3.2.13 on 2022-07-21 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_biz_info_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ceo_id_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proof_of_business',
        ),
        migrations.CreateModel(
            name='ProofBusinessAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], default='Image', max_length=200)),
                ('file', models.FileField(null=True, upload_to='business_ownership_attachments')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IDCardsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], default='Image', max_length=200)),
                ('file', models.FileField(null=True, upload_to='id_cards_attachments')),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
