# Generated by Django 3.2.13 on 2022-07-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220721_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biz_info_verified',
            field=models.BooleanField(default=False),
        ),
    ]
