# Generated by Django 3.2.13 on 2022-07-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220721_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcardsattachment',
            name='file',
            field=models.FileField(null=True, upload_to='id_cards_attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='proofbusinessattachment',
            name='file',
            field=models.FileField(null=True, upload_to='business_ownership_attachments/%Y/%m/%d/'),
        ),
    ]
