# Generated by Django 3.2.13 on 2022-08-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220818_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_expires_at',
        ),
    ]
