# Generated by Django 3.2.13 on 2022-08-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_user_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
