# Generated by Django 3.2.13 on 2022-09-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productcountviews_slug'),
        ('accounts', '0017_auto_20220908_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='variant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.variant'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
