# Generated by Django 3.2.13 on 2022-10-01 19:30

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20221001_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 557434, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 557456, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nda',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 562042, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nda',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 562061, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 562400, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 562419, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 560290, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 560311, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 553750, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 553694, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 553762, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='NDAPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(default='', max_length=200)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 562851, tzinfo=utc))),
                ('updated_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 4, 562867, tzinfo=utc))),
                ('expires_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 1, 19, 30, 4, 562878, tzinfo=utc))),
                ('nda_bought', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.nda')),
                ('nda_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.ndauser')),
            ],
        ),
    ]
