# Generated by Django 3.2.13 on 2022-10-01 19:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20221001_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 747035, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 747056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nda',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 751556, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nda',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 751584, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 752437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='expires_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 1, 19, 30, 57, 752463, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 752453, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 751981, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 752000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 749700, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 749720, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 743188, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 743122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 743216, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='NDAProposals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=None)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=100)),
                ('decline_reason', models.CharField(choices=[('Shady Proposal', 'Shady Proposal'), ('Has Previous Scam History', 'Has Previous Scam History'), ('I am Uninterested', 'I am Uninterested')], default='', max_length=500)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 752965, tzinfo=utc))),
                ('updated_at', models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 30, 57, 752981, tzinfo=utc))),
                ('from_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='accounts.ndauser')),
                ('to_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='recepient', to='accounts.ndauser')),
            ],
        ),
    ]
