# Generated by Django 3.2.13 on 2022-10-01 19:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20221001_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 131909, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 131932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nda',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 136423, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nda',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 136443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndaproposals',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 137845, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndaproposals',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 137862, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 137181, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='expires_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 1, 19, 32, 52, 137208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 137197, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndatransferhistory',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 138330, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndatransferhistory',
            name='to_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='hist_recepient', to='accounts.ndauser'),
        ),
        migrations.AlterField(
            model_name='ndatransferhistory',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 138347, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 136750, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 136766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 134816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 134839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 128752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 128698, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 32, 52, 128764, tzinfo=utc)),
        ),
    ]
