# Generated by Django 3.2.13 on 2022-10-01 19:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20221001_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 213203, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 213225, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nda',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 217558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nda',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 217577, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndaproposals',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 218897, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndaproposals',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 218913, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 218367, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='expires_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 1, 19, 33, 39, 218392, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 218382, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndatransferhistory',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 219420, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndatransferhistory',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 219436, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 217909, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 217928, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 215837, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 215855, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 208912, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 208863, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 19, 33, 39, 208924, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='NDAAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], default='document', max_length=200)),
                ('file', models.FileField(null=True, upload_to='nda_attachments/%Y/%m/%d/')),
                ('nda', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.nda')),
            ],
        ),
    ]
