# Generated by Django 3.2.13 on 2022-10-01 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20221001_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 579068, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 579091, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nda',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nda',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ndaproposals',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 584967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndaproposals',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 584989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 584286, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='expires_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 11, 1, 21, 36, 10, 584313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 584302, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndatransferhistory',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 585498, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndatransferhistory',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 585515, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 583837, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 583856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 581806, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 581827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 576045, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 575982, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 10, 1, 21, 36, 10, 576057, tzinfo=utc)),
        ),
    ]
