# Generated by Django 3.2.13 on 2022-10-02 22:44

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20221001_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='ndauser',
            name='nda_bought',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 650230, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 650257, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndaproposals',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 655575, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndaproposals',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 655592, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 654974, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 22, 44, 23, 655087, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndapurchases',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 655074, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndatransferhistory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 656088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndatransferhistory',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 656105, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 654531, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 654548, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 652722, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 652742, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 647394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 647343, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 2, 22, 44, 23, 647407, tzinfo=utc)),
        ),
    ]
