# Generated by Django 3.2.13 on 2022-10-02 22:51

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20221002_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndapurchases',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 22, 51, 33, 463562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ndauser',
            name='nda_bought',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
