BBBB BBBBBBBBBBBBB

BBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFF FFFFFFF
    XXXXXX
  XXXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFF FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    XXXXXX
    XXXX XXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFF FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    XXXXXX

    XXXX XXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
        FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
      XXXXXX
  XXXXXX
XXXXXX

XXXX XXXXX X XXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXX XXXXX X XXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXX XX
XXXXXX