BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXX X XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
                  XXXX
                    XXXXXXXXXX
                    XXXXXXXX XXXXXXXXXXX
                    XXXXXXXXXXXXXXX
                  XXXXX
                XXXXXXXX
                XXXXXXX
                  BBB BBBBBBBBBBB BB BBBBBBBBBBBB
                  XXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXXX
                  XXXXX
                  BBBBBB
                XXXXXXXX
              XXXXXXXX

            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB

  XXXXXX
XXXXXX
BBBBBBBB
