# Generated by Django 3.2.13 on 2022-07-21 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_proof_of_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_manager_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_manager_phone_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='account_manager_phone_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ceo_id_card',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city_location',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_address_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_address_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_ceo_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_mailing_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contact_preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_existing_shop',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proof_of_business',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referrer_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='store_name',
        ),
    ]
