# Generated by Django 3.2.13 on 2022-08-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220722_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
