# Generated by Django 3.2.13 on 2022-08-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='otp_expires_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
