BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB
    BBBB BBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
        XXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
            
                    XXXX XXXXXXXXXXXXXXXXXXXXX
            
                        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
                                BBBBBBBBBB
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXX
                                XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
            
                                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX
                            XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXXX
    XXXXXXX

BBBBBBBB