BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB
    BBBB BBBBBB
    BBBB BBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
    XXXXXX
        XXXXXXXX XXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXXXX
            
                    XXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
                                BBBBBBBBBB
                                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
                                FFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                                FFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                                
                                XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX XXXX X XXXX XXXXX XXXXXXX XXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                XXXXXXXXX
                                FFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

                                FFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
                                FFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF FFFFFFFFF

                                XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXX XXXX
                            XXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXX
                                XXXXX XXXXXXX XXX XXX XXXXX XX XXX XXXXXX XXXXXXXXXXXXXX XX XXXXXXXXXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXXXXXX
    XXXXXXX

BBBBBBBB
