BBBB BBBBBBBBBBBBB

BBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      FFFFFFFFFFFFFFFFFFFFFFFF
      XXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
      
    XXXXXX
  XXXXXX
XXXXXX

XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XX

XXXX XXXXX X XXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXX XXXXX X XXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXXX XX
XXXXXX