BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXX X XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX

          XXXXXX
          XXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXX X XBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
                XXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
              XXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
