BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB
  BBBB BBBBBB
  BBBBBB BBBBBBBB BB BBBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
  XXXXXX XXXXXXXXXXXXXXXX
    XXXXXXXXX
      XXXXXXX XXXXX
    X
  XXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXX
              XXX XXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXX
            XXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXX
          XXXX XXXXXXXXXXXX XXXXXXX XXXXXXXXX
            XXXXX
              XXXX
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                    BBB BBBBBBBB BB BBBBBBBBBB
                      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBB
                  XXXXX
                XXXXX
                
                XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXXX XXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX

                    BBB BBB BB BBBB
                      XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
                    BBBBBB
                  XXXXX
                XXXXX
              XXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
              
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXX XXXXXXXX XXXXXXXBB B BB BBB BBBBBBBBBX XXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                      XXXXXXX XXXXXXXX XXXXXXXXXXBB BBBBBBBBBB BB BBBB XXXXXXXXXX BBBBBXXXXXX XXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXBB BBBBBBBBBB BB BBBBBBBBBBBXXXXXXXXXXBBBBBX XXXXX XXXXXXXXXXXX
                      XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXBB BBBBBBBBBB BB BBBBBBBBBBBBXXXXXXXXXXBBBBBXXXXXX XXXXXXXXXXXX
                    XXXXXXXXX
                  XXXXXX
                XXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXX
              BB BBBBBBBBBBBBBB B B
                BBB BBBBBBB BB BBBBBBBB
                  XXXX XXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBB BBBBBBBBBBBBXX
                          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXX
                          BBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXX
                          BBBBB
                        XXXX
                      XXXXXX
                      XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXXXX
                          
                          XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX                
                        XXXXXX
                        XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXX XX XXXXXXXXXXXXXX
                      XXXXXX
                      
                      XXXX XXXXXXXXXXXXXX XXXX
                        XX XXXXXXBBB BBBBBBBBB BBBBBBBBBBBBX XXXXXXXXXXX XXXXXX
                          XXXXXX
                            XXXXX XXXXXXXXXXXXXXX XX XXXX XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                            XXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                          XXXXXXX
                        XXXX
                        BB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX   
                        BBBB
                          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX   
                        BBBBB
                        XX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                      XXXXXX
                      XXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                        XX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                      XXXXXX
                    XXXXX
                  XXXXXX
                BBBBBB
              BBBB
                XXXX XXXXXXXXXXXXXXXXXX
                  XXX XXXXXXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXX
              BBBBB
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX
  XXXXXX XXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XX

  XXXXXXX
XXXXXXX

XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB