BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB

XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXX X XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX
            XXXXX XXXXXX X XBBB BBBBBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXX
                  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB
                XXXXXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB
              XXXXXX
            XXXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
