BBBBBBB BBBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXX X XXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXXX
                  XXXX
                    XXXXXXXXXX
                    XXXXXXXXX XXXXXXXXX
                    XXXXXXXXXXXXX
                    XXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                    XXXXXXXXXXXXXXXX
                  XXXXX
                XXXXXXXX
                XXXXXXX
                  BBB BBBBBBB BB BBBBBBBBB
                  XXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBB BBBBBBB BBBBBBBBBBXXXXXXXXXXXXXXX
                  XXXXX
                  BBBBBB
                XXXXXXXX
              XXXXXXXX

              XX XXXXXXBBB BBBBBBBBBBBBBBBBBB BBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBB

  XXXXXX
XXXXXX
BBBBBBBB
