BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB
  BBBB BBBBBB

  BBBB BBBBBBBBBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB
  XXXXX
  XXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXX

          XXXX XXXXXXXXXXXXXXXXXXXX
            BBBBBBB BBBBBBBBBBBBBBBBBBB BBBB
              XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX XXXXXXX
               #

            BBBB
              XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXX XXXXXXX

              XXXX XXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXX
            BBBBBBBBBB
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXX
              XX XXXXXXXXXX XXXXXXXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
            
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXX XXXXXXXXXXXXX
              XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX

        XXXXXX
        
        XXXX XXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBBBBB BB BB  BBBB XXX BBBBBXXXX
              XX XXXXXXXXXXXXXXXXXXXX  XXXXXXXXXXXXX XXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
                XX XXXXXXXXXXXXXXXX
                  FFFFFFFFFFFFFFFF
                XXXX
                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX

              XXXXXX
            XXXXXX
          XXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            
            XXXX XXXXXXXXXXXX
              XXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
              XXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXX
              
              XXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXX
                XXXX XXXXXXXXXXXXXXXXXX
                  XXXXXXXXXX XXXXXXXXXXXXX
                  XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX
                    BBBBBBBBBB
                      XXXX XXXXXXXXXXXXXXXXXXX
                        XXXX XXXXXXXXXXXX
                          XXXX XXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXX X XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XX
                            XXXX
                          XXXXXX
                        
                          XXXX XXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXXXX XXXX X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXX XX
                            XXXX
                          XXXXXX
                          XXXX XXXXXXXXXXXXXXXXXX
                            XXXXXX XXXXXXXXXXXXX XXXXX X XXXX XXXXXXXXXXX XXXXXXX XXXXX XXXXXXXX XXXXXXXX XX
                          XXXXXX
                        XXXXXX
                      XXXXXX
                    XXXXXX
                  XXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
        XXXXXX
      XXXXXX
    XXXXXXXXXX
  XXXXXXX


  XXXXXXXX
    XXXXXXX XX XXXXXXXXXXXXXXXXXXXXX X
      XXXXXXX
      XXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXX
    XXX

    XXXXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXX
    XXXXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXX X XXXXXXX
      XXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    X
    XXXXXXXX

    XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX XXXXXXXXX X
      XXXXXXXXXXX X XXXXXXXXXXXXXX

      XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX X XXXXXX
      XXXXXXXXXXXXX XX XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
    X

    XXXXXXXXXX

    XXXXXXXX XXXXXXXXXXX X
      XXXXXXXXXXXXX X XXXXXXXXXXXX
      XXXXXXXXXXXXX XX
      XXXXXXXX X XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXX
      XXX
    X
    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXX
    X

  XXXXXXXXX
BBBBBBBB