BBBBBBB BBBBBBBBBBBBBBBBBBBB
BBBBB BBBBBBBBBBBB
  BBBB BBBBBB

  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB


XXXXXX
  XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXX
        BB BBBBBBBBBBBBBBBBB B B
          BBB BBBBBBBBBB BB BBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXX XX X XXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBXXXXXXX XXXXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXX XXXXXXXXXX
                      XXXX XXXXXXXXXXXXXX
                        XX XXXXXXBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
                          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB BB BBBB
                            XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXX
                          BBBB
                            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXX XXXXXX XXXXXX XXXXXX XXXXXXX
                          BBBBB
                        XXXX
                      XXXXXX
                      XXXX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX X XXXX XXXXXXXFFFFFFFFFFFFFFFFXXXXXXXXXXXXXXXXXXXXXXX
                      XXXX XXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXXXX
                    XXXXXX
                  XXXXXX
                  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                    BB BBBBBBBBBBBBBBBBBBBBB
                      XXXXXXXXXXXXXX XX  XXXX XXXXXXXXXXX XXXX XXX XXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBB
                      XXXXXXXXX XXXXXX XX  XXXX XXXXXXXXXXX XXXXX XX XXXXX XXXXXXXXXXXXXXXXXXXXXXX
                    BBBBB
                  XXXXXX

                XXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                  XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX
                XXXXXX
              XXXXXX
            XXXXXX
          BBBBBB
          BBBB
            XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
              XXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
            XXXXXX
          BBBBB  
        XXXXXX
      XXXXXX
    XXXXXX
  XXXXXXXXXX
XXXXXXX
BBBBBBBB