BBBBBBB BBBBBBBBBBBBBBBBBBBB

BBBBB BBBBBBBBBBBB
  BBBB BBBBBB
  BBBBBBB BBBBBBBBBBBBBBBBBBBBBBB

  XXXXXX
    XXXXXXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXX
          XXXXX
        XXXXXX
      XXXXXX

      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXX XX XXXXXXXX XXXXXXXXXXXXXXXX
          BBB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBBBBB
            XXXX XXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXX
                XX XXXXXXBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX XXXXXXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXX
                  XX XXXXXXBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXX
                  XXXXXXXFFFFFFFFFFFFFFFFXXXXXXXX
                XXXXX
                XX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXX
                XX XXXXXXBBB BBBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXX XXXXXXX
              XXXXXX
            XXXXXX
          BBBBBB
        XXXXXX
      XXXXXX
    XXXXXXXXXX
  XXXXXXX

  XXXXXXXX
    XXXXXXXXXXXXXXXXXXXXXXXXXXX X
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXX
  XXXXXXXXX
BBBBBBBB