# Generated by Django 3.0.6 on 2020-07-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200705_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(default='KRVg75zvbp44zdhRvEfaKWDJWluKWtwi', editable=False, max_length=32, unique=True),
        ),
    ]
