# Generated by Django 3.0.6 on 2020-07-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200705_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='USD', editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(default='IdmLVqHpQKFWdXdd29VYG258w7575Re9', editable=False, max_length=32, unique=True),
        ),
    ]
