# Generated by Django 3.0.6 on 2020-07-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200708_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.CharField(default='5SoW6fz4g2N2ed8Es9eCH5p1s5rUJQpf', editable=False, max_length=32, unique=True),
        ),
    ]
