# Generated by Django 3.0.6 on 2020-07-25 23:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200622_2254'),
        ('orders', '0010_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cart', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Cart')),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Variant')),
            ],
        ),
    ]
