# Generated by Django 3.0.6 on 2020-08-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_stripe_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='lineitem',
            name='currency',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
