# Generated by Django 3.0.6 on 2020-08-19 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200802_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_transaction_id',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number_last_4', models.CharField(editable=False, max_length=4)),
                ('card_cvv', models.CharField(editable=False, max_length=4)),
                ('card_brand', models.CharField(editable=False, max_length=32)),
                ('card_expiry_month', models.CharField(editable=False, max_length=2)),
                ('card_expiry_year', models.CharField(editable=False, max_length=4)),
                ('transaction_id', models.CharField(editable=False, max_length=32)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
