# Generated by Django 3.0.6 on 2020-08-19 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_order_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card_cvv',
        ),
    ]
