# Generated by Django 3.0.6 on 2020-11-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20201120_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='option_value',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
