# Generated by Django 3.0.6 on 2020-11-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_cartitem_option_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='option_type',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
