# Generated by Django 3.0.6 on 2021-01-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210106_1225'),
        ('orders', '0026_auto_20201125_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card_expiry_month',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card_expiry_year',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card_number_last_4',
        ),
        migrations.AddField(
            model_name='transaction',
            name='credit_card',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.CreditCard'),
        ),
    ]
