# Generated by Django 3.0.6 on 2021-02-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20210106_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='tracking_number',
            field=models.CharField(blank=True, default='N/A', max_length=32, null=True),
        ),
    ]
