# Generated by Django 3.0.6 on 2021-03-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_lineitem_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
