# Generated by Django 3.1.5 on 2021-06-09 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_lineitem_dispatched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='endless_factory_cut',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
