# Generated by Django 3.1.5 on 2021-06-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_order_endless_factory_cut'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='courier_agency',
            field=models.CharField(blank=True, default='N/A', max_length=32, null=True),
        ),
    ]
