BBBB BBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXX XXX
    XXXXX XXXXXXXXXXXXX XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXX

    XXXX XXXX XXX XXX

    XXXX XXXX XXX XXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX

    XXXXXXXXXXXXXX XXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
 XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX
            XXXX XXXXXX XXXXX XXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXXXX XXX XXX

            XXXX XXXX XXX XXXXX XXX
            BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB
            XXXX XXXX XXX XXX XXX

            XXXX XXXX XXXXXXXXX XXXXX XXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBBBB BB BBBBBBBB
                    XXXXXXXXXXXXXXXXXXXXXXXXXXX
                BBBBBB
                XXXX XXXXXXX XXXXXXX XXXXX XXX
                
                BBBBB BBBBBBBBBBBB
                    
                BBBBBBBB
                XXXX XXXXXXX XXXXXXX XXX XXX

                XXXX XXXXXX XXXXX XXX
                BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
                XXXX XXXXXX XXX XXX

            XXXXXX
          
            XXXX XXXXX XXXX XXX XXX
        XXXXXX
    XXXXXX

    XXXX XXXX XXXXXXX XX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXX XXXX XX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    XXXX XXXX XX XXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBXXXXXXXXXXX

XXXXXXX
XXXXXXX
