BBBB BBBBBB
XXXX XXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXX XXXXXXXXXXX
    XX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXX  XXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXX
    XXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXX
        XXXX
      XXXXX
      XXX XXXXXXXXXXXXXXXXXXXXXX
        XX XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXX
        XXXX
      XXXXX
       #

    XXXXX
    XXX XXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXXXXXXXX  XXXXXX XXXXXXXX
            XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXX
          XXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXX
          XXXX XXXXXXXXXXXXX XXXXXX XXXXXX XXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBBBBBBB BB BBBB
                  XXXX XXXXXXXXXXXXX XXXXXXX
                BBBB
                  XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBX XXXXXXX
                BBBBB
              XXXXXX
              XXXX XXXXXXXXXXXXXXX
                XX XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
              XXXXXX
            XXXXXX
          XXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XX XXXX X XBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXX
            XX XXXX X XXX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXXXXX XX XXXXXXXX
            XX XXXXXXBBB BBBBBBBBX XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXX XXXXXXXX
              XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                  XX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                  XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
              XXXXXX
            XXXX
          XXXXXX
        BBBBB
      XXXXX
    XXXXX
  XXXXXX
XXXXXX
