# Generated by Django 3.2.13 on 2022-07-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220725_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='business_source',
            field=models.CharField(default='N/A', max_length=250),
        ),
    ]
