# Generated by Django 3.2.13 on 2022-07-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220722_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business_source',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
