# Generated by Django 3.2.13 on 2022-09-06 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220902_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
