# Generated by Django 3.2.13 on 2022-09-08 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_variant_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcountviews',
            name='product_uid',
        ),
        migrations.AddField(
            model_name='productcountviews',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AddField(
            model_name='productcountviews',
            name='session',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
