# Generated by Django 3.2.13 on 2022-09-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productcountviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcountviews',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
