# Generated by Django 3.2.13 on 2022-09-09 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productcountviews_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='initial_stock',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
