# Generated by Django 3.2.13 on 2022-09-13 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_delete_recentlyviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.IntegerField(default=-1),
        ),
        migrations.CreateModel(
            name='VariantAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video')], default='Image', max_length=200)),
                ('file', models.FileField(null=True, upload_to='media/product_attachments')),
                ('variant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.variant')),
            ],
        ),
    ]
