# Generated by Django 3.2.13 on 2022-09-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220913_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.CharField(default='NULL', max_length=255, null=True),
        ),
    ]
